---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes


spec:
  selector:
    matchLabels:
      app: springboot-kubernetes
  replicas: 1

  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      restartPolicy: Always
      containers:
        - name: springboot-kubernetes
          image: boot:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:   # Setting Environmental Variables
            - name: USER_INFO_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: userinfoHost
            - name: USER_INFO_PORT # Setting Database password
              value: "8083"
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: springit
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: ahmad11exalt
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: eurekaHost
            - name: EUREKA_PORT # Setting Database password
              value: "8081"



---
apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes-service

spec:
  ports:
    - protocol: "TCP"
      port: 8085        # The port inside the cluster
      targetPort: 8085  # The port exposed by the service
  type: LoadBalancer        # Type of service
  selector:
    app: springboot-kubernetes
---
