apiVersion: v1
kind: Service
metadata:
  name: mysql2
  labels:
    app: mysql2
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql2
    tier: database
  clusterIP: None # DNS is used, so clusterIP is not needed


---
# Define a 'Persistent Volume Claim'(PVC) for MySQL Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql2-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mysql2
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.

---
# Deployment specification begins here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2
  labels:
    app: mysql2
    tier: database
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: mysql2
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql2
        tier: database
    spec:
      containers:
        - name: mysql2
          image: mysql #image from docker hup
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ahmad11exalt
            - name: MYSQL_DATABASE
              value: userinfo
          ports:
            - containerPort: 3306
              name: mysql2
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql2-persistance-storage
      volumes:
        - name: mysql2-persistance-storage
          persistentVolumeClaim:
            claimName: mysql2-pv-claim
